export enum ActionEnum{
    FIRST_CONNEXION="FIRST_CONNEXION",
    RESET_PASSWORD= "RESET_PASSWORD"
    
}

export enum Status{
    OK = "OK",
    BAD_REQUEST = "BAD_REQUEST", 
    UNAUTHORIZED = "UNAUTHORIZED", 
    VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION", 
    EXCEPTION = "EXCEPTION", 
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS", 
    ACCESS_DENIED = "ACCESS_DENIED"
}